l10n: ensure gettext is the correct version

diff --git a/pootle/tools/createpootlepot b/pootle/tools/createpootlepot
--- a/pootle/tools/createpootlepot
+++ b/pootle/tools/createpootlepot
@@ -20,6 +20,12 @@ PACKAGE="Pootle"
 VERSION=$(python -m pootle.core.utils.version main)
 MSGID_BUGS_TO="https://github.com/translate/pootle/issues/new"
 
+REQUIRED_GETTEXT_VERSION=0.19.7
+if [[ $(xgettext --version | head -1 | sed 's/^[^0-9]*//') < "$REQUIRED_GETTEXT_VERSION" ]]; then
+    echo "Gettext >=$REQUIRED_GETTEXT_VERSION required"
+    exit 1
+fi
+
 cd $SRC_DIR
 
 # Common folders to ignore when extracting
diff --git a/pootle/tools/updatepootlepo b/pootle/tools/updatepootlepo
--- a/pootle/tools/updatepootlepo
+++ b/pootle/tools/updatepootlepo
@@ -2,6 +2,12 @@
 
 L10N_DIR=pootle/locale
 
+REQUIRED_GETTEXT_VERSION=0.19.7
+if [[ $(xgettext --version | head -1 | sed 's/^[^0-9]*//') < "$REQUIRED_GETTEXT_VERSION" ]]; then
+    echo "Gettext >=$REQUIRED_GETTEXT_VERSION required"
+    exit 1
+fi
+
 cd $L10N_DIR
 for lang in $(find . -type d -mindepth 1 -maxdepth 1 | egrep -v "templates")
 do
